---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polaris
  name: polaris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polaris
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/serveradmin-default: "true"
        app: polaris
    spec:
      containers:
        - image: ogarcia/polaris
          name: polaris
          ports:
            - containerPort: 5050
          resources:
            limits:
              cpu: "2000m"
              memory: "2048Mi"
          volumeMounts:
          - name: datavol
            mountPath: /var/lib/polaris
          - name: cachevol
            mountPath: /var/cache/polaris
          - name: musicdir
            mountPath: /music
      volumes:
      - name: datavol
        nfs:
          server: 192.168.1.10
          path: /mnt/servicesTank/polaris
          readOnly: false
      - name: cachevol
        nfs:
          server: 192.168.1.10
          path: /mnt/servicesTank/polaris/cache
          readOnly: false
      - name: musicdir
        nfs:
          server: 192.168.1.10
          path: /mnt/cpool1/media/music/Music
          readOnly: true
      restartPolicy: Always
status: {}


---
kind: Service
apiVersion: v1
metadata:
  name: polaris-tcp       # < name of the service
#  namespace:              # < namespace where to place service
  annotations:
    metallb.universe.tf/allow-shared-ip: polaris # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
spec:
  selector:
    app: polaris           # < reference to the deployment (connects the service with the deployment)
  ports:
  - port: 5050             # < port to open on the outside on the server
    targetPort: 5050       # < targetport. port on the pod to passthrough
    name: http-tcp         # < reference name for the port in the deployment yaml
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.3.83 # < IP to access your jellyfinserver. Should be one from the MetalLB range and the same as the TCP yaml
  sessionAffinity: ClientIP #

---
kind: Service
apiVersion: v1
metadata:
  name: polaris-udp       # < name of the service
#  namespace:              # < namespace where to place service
  annotations:
    metallb.universe.tf/allow-shared-ip: polaris # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
spec:
  selector:
    app: polaris           # < reference to the deployment (connects the service with the deployment)
  ports:
  - port: 5050             # < port to open on the outside on the server
    targetPort: 5050       # < targetport. port on the pod to passthrough
    name: http-udp         # < reference name for the port in the deployment yaml
    protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 192.168.3.83 # < IP to access your jellyfinserver. Should be one from the MetalLB range and the same as the TCP yaml
  sessionAffinity: ClientIP #